# Generated by Django 4.0.4 on 2022-05-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('address', models.TextField(max_length=200, null=True)),
                ('enrollment', models.CharField(max_length=20)),
                ('discipline', models.CharField(choices=[('bsit', 'BSIT'), ('bscs', 'BSCS'), ('bsse', 'BSSE'), ('bsds', 'BSDS'), ('bsai', 'BSAI')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('address', models.TextField(max_length=200, null=True)),
                ('department', models.CharField(choices=[('cs', 'Computer Science'), ('eng', 'English'), ('math', 'Mathematics'), ('chm', 'Chemistry'), ('phy', 'Physics')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
